version: '3.8'

services:
  monitoring_service:
    build: ./monitoring_service
    container_name: monitoring_service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: secret
      SPRING_DATA_MONGODB_DATABASE: secret
      
      MONITORING_MQTT_BROKER: ssl://82d60bde50f04e3e80b0904f43cdcd44.s1.eu.hivemq.cloud:8883
      MONITORING_MQTT_USERNAME: Access_2
      MONITORING_MQTT_PASSWORD: Access_2
      MONITORING_MQTT_CLIENT_ID: access_monitoring_service
    networks:
      - yanapay-net

  yanapay_backend:
    build: ./yanapay
    container_name: yanapay_backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: secret
      SPRING_DATASOURCE_USERNAME: secret
      SPRING_DATASOURCE_PASSWORD: secret

      SPRING_DATA_MONGODB_URI: secret
      SPRING_DATA_MONGODB_DATABASE: secret_db
      
      YANAPAY_MQTT_BROKER: ssl://82d60bde50f04e3e80b0904f43cdcd44.s1.eu.hivemq.cloud:8883
      YANAPAY_MQTT_USERNAME: Access_1
      YANAPAY_MQTT_PASSWORD: Access_1
      YANAPAY_MQTT_CLIENT_ID: access_yanapay_service
    networks:
      - yanapay-net

networks:
  yanapay-net:
    driver: bridge